from django.urls import path

from menu import views

urlpatterns = [
    path('main/', views.main),
    path('about/', views.about),
    path('services/', views.services),
    path('web-development/', views.web_development),
    path('web-design/', views.web_design),
    path('ux-ui-design/', views.ux_ui_design),
    path('prototyping/', views.prototyping),
    path('layout-design/', views.layout_design),
    path('user-experience-testing/', views.user_experience_testing),
    path('graphic-design/', views.graphic_design),
    path('logos/', views.logos, name='logos'),
    path('concept-development/', views.concept_development, name='concept-development'),
    path('sketching/', views.sketching, name='sketching'),
    path('illustrations/', views.illustrations, name='illustrations'),
    path('vector-images/', views.vector_images, name='vector-images'),
    path('raster-graphics/', views.raster_graphics, name='raster-graphics'),
    path('web-programming/', views.web_programming),
    path('front-dev/', views.front_dev),
    path('html-css/', views.html_css),
    path('flexbox/', views.flexbox),
    path('grid/', views.grid),
    path('javascript/', views.javascript),
    path('es6/', views.es6),
    path('reactjs/', views.reactjs),
    path('back-dev/', views.back_dev, name='back-dev'),
    path('php/', views.php, name='php'),
    path('laravel/', views.laravel, name='laravel'),
    path('symfony/', views.symfony, name='symfony'),
    path('python/', views.python, name='python'),
    path('django/', views.django, name='django'),
    path('flask/', views.flask, name='flask'),
    path('marketing/', views.marketing),
    path('seo/', views.seo),
    path('keyword-analysis/', views.keyword_analysis),
    path('market-research/', views.market_research),
    path('query-selection/', views.query_selection),
    path('content-optimization/', views.content_optimization),
    path('meta-tags-improvement/', views.meta_tags_improvement),
    path('quality-content-creation/', views.quality_content_creation),
    path('smm/', views.smm),
    path('social-media-ads/', views.social_media_ads),
    path('ad-campaigns-creation/', views.ad_campaigns_creation),
    path('audience-targeting/', views.audience_targeting),
    path('content-plans/', views.content_plans),
    path('content-planning/', views.content_planning),
    path('effectiveness-analysis/', views.effectiveness_analysis),
    path('portfolio/', views.portfolio),
    path('blog/', views.blog),
    path('contacts/', views.contacts),
    path('faq/', views.faq),
    path('item1/', views.item1, name='item1'),
    path('item2/', views.item2, name='item2'),
    path('item3/', views.item3, name='item3'),
    path('item4/', views.item4, name='item4'),
    path('item5/', views.item5, name='item5'),
]